spring.jpa.hibernate:
                ddl-auto: update
spring:
  datasource:
           url: jdbc:mysql://localhost:3306/springclouddemo
                
spring.datasource:
               username: root
spring.datasource.password: root

eureka:
   client:
     serviceUrl:
           defaultZone: http://localhost:8090/eureka
   instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
 
ribbon:
    eureka:
        enabled: true
